app_login:
  path: /api/login
  methods: POST

app_register:
  path: /api/register
  methods: POST
  controller: App\Domain\User\Controller\Register

app_email_verify:
  path: /api/register/verify/{token}
  methods: GET
  controller: App\Domain\User\Controller\VerifyAccount
  requirements:
    token: '.*'

app_protected:
  path: /api/protected/hello
  methods: GET
  controller: App\Domain\User\Controller\ProtectedController

default:
  path: /default
  controller: App\Controller\DefaultController::index
checkout:
  path: /api/create-checkout-session/{amount}
  controller: App\Controller\DefaultController::checkout
success:
  path: /success
  controller: App\Controller\DefaultController::success
error:
  path: /error
  controller: App\Controller\DefaultController::error
