security:
    providers:
        user_provider:
            entity:
                class: App\Domain\User\Model\User
                property: email

    encoders:
        App\Domain\User\Model\User:
            algorithm: auto
            cost: 13
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            user_checker: App\Domain\User\Security\UserLoginChecker
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            anonymous: ~
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    # Just add a protected route to test only authenticated user can access it
    access_control:
        - { path: ^/api/protected, roles: ROLE_USER }
